//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_main
    {
        public int id { get; set; }
        public Nullable<int> id_order { get; set; }
        public Nullable<double> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> id_stock_items { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual stock_items stock_items { get; set; }
    }
}
