//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.stock_items = new HashSet<stock_items>();
        }
    
        public int id { get; set; }
        public string name_product { get; set; }
        public Nullable<int> id_categore { get; set; }
        public Nullable<int> id_subcategory { get; set; }
        public string image { get; set; }
        public Nullable<int> id_production { get; set; }
        public string description { get; set; }
        public string composition { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual categorys categorys { get; set; }
        public virtual subcategorys subcategorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_items> stock_items { get; set; }
    }
}
