//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stock_items()
        {
            this.orders_main = new HashSet<orders_main>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_production { get; set; }
        public Nullable<int> id_size { get; set; }
        public Nullable<double> quantity_for_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders_main> orders_main { get; set; }
        public virtual productions productions { get; set; }
        public virtual products products { get; set; }
        public virtual sizes sizes { get; set; }
    }
}
